title: Camille Ogden
#logo: /assests/img
#description: text below image
"With a background in marketing, management, and analytics, along with a degree in Business and specialized training in data science, I am well-prepared for a Data Analyst role. My proven analytical skills, proficiency in data science tools, and commitment to continuous learning position me to contribute effectively to data-driven decision-making in your team."

#show_downloads: false
theme: jekyll-theme-minimal
